name: dns
on:
  schedule:
    - cron: 0 * * * *
  workflow_dispatch: {}
  push:
    paths:
      - .github/workflows/dns.yml
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      RAW_DIR: data/dns/raw
      TOKEN: ${{secrets.TOKEN}}
      API: ${{secrets.API}}
    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          token: ${{secrets.PAT}}
      - name: ensure dirs
        run: mkdir -p "${RAW_DIR}/records" && mkdir -p data/dns/records
      - name: get zones
        run: |
          ZONES_FILE="${RAW_DIR}/zones.json"
          curl -X GET "${API}/zones" \
          -H "Authorization: Bearer $TOKEN" \
          -H "Content-Type:application/json" | jq --indent 2 '.result[] |= (if .development_mode? and (.development_mode < 0) then .development_mode = "-" else . end) | .result'> "$ZONES_FILE"
          node index.js "$ZONES_FILE"
      - name: get records by zone id
        run: |
          JSON=$(cat data/dns/raw/zones.json)
          echo json: $JSON
          IDS=$(echo "$JSON" | jq -r '.[].id')
          echo ids: $IDS

          for ID in $IDS; do
            NAME=$(echo "$JSON" | jq -r --arg zoneId "$ID" '.[] | select(.id == $zoneId) | .name')
            echo name: $NAME
            URL="${API}/zones/${ID}/dns_records?per_page=500"
            echo url $URL

            curl -X GET $URL \
              -H "Authorization: Bearer $TOKEN" \
              -H "Content-Type: application/json" | jq --indent 2 '.result' > "${RAW_DIR}/records/${NAME}.json"
            node index.js "${RAW_DIR}/records/${NAME}.json"
          done
      - name: Set current date as env variable
        run: echo "NOW=$(date +'%Y-%m-%d %H:%M')" >> $GITHUB_ENV
      - name: push
        uses: cpina/github-action-push-to-another-repository@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.PAT }}
        with:
          source-directory: data
          destination-github-username: ${{ secrets.USER }}
          destination-repository-name: data-cf-dns
          commit-message: Updated DNS data $NOW
          target-branch: main
